#!/bin/bash

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

if [[ "$(uname)" == "Darwin" ]]; then
	brew install stow
fi

stow -R -v -t ~ -d ~/dev/environment/home .
