#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10
